# -*- mode: ruby -*-
# vi: set ft=ruby :


# https://gist.github.com/3798773
#
# Mounts caches debian downloads and remount the cache to speed up later
# "vagrant destroy -f && vagrant up" operations.
#
def local_cache(box_name)
  cache_dir = File.join(File.expand_path(Vagrant::Environment::DEFAULT_HOME),
                        'cache',
                        'apt',
                        box_name)
  partial_dir = File.join(cache_dir, 'partial')
  FileUtils.mkdir_p(partial_dir) unless File.exists? partial_dir
  $stdout.write("Apt cache dir on host is: #{cache_dir}\n")
  cache_dir
end


Vagrant::Config.run do |config|

  # #config.vm.customize ["modifyvm", :id, "--memory", 1024]
  config.vm.box = "precise32"

  # https://gist.github.com/3798773
  cache_dir = local_cache(config.vm.box)
  config.vm.share_folder "v-cache", "/var/cache/apt/archives/", cache_dir

  config.vm.boot_mode = :gui
  config.vm.host_name = "notepad"
  config.vm.network :hostonly, "192.168.43.176"

  # mount the puppet files used to configure services and other things:
  config.vm.share_folder "files", "/vagrant/files", "../puppet/files"

  # Share the developers home folder so its accessible from the machine. This
  # can be used to copy in ssh keys and other set up needed to checkout code.
  config.vm.share_folder "dev_home", "/home/vagrant/dev_home", ENV['HOME'] #, { :nfs => true,  }

  config.vm.provision :puppet, :options => "--verbose --debug" do |puppet|
  # config.vm.provision :puppet do |puppet|
    puppet.manifests_path = ENV['PUPPET_MANIFESTS'] || "../puppet/manifests"
    puppet.module_path = ENV['MODULE_PATH'] || "../puppet/modules"
    puppet.manifest_file  = "ipynotepad.pp"
  end

end
